#include <stdio.h>
#include <stdlib.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

/* Simple main program which sleeps for 1 second and prints the
 * process ID of the process generated by the fork() call.
 *
 * Makes exactly eight system calls (eight more system calls
 * than an empty program makes)
 */
int main()
{
	struct timespec t = {0};

	t.tv_sec = 1;
	t.tv_nsec = 0L;

	nanosleep(&t, NULL);

	pid_t pid = fork();
	int status;

	if (pid != 0)
	{
		printf("%d\n", getpid());
		waitpid(pid, &status, 0);
	}

	return 0;
}
